-- 000001_initial_schema.up.sql
--
-- Initiales DB-Schema des Go-Ports, 1:1 aus der Python/Django-Version.
--
-- Herkunft: erzeugt durch `python manage.py migrate` aller 61 gui-Migrationen
-- (0001-0061) gegen postgresql, dann `pg_dump --schema-only` der gui_*-Tabellen.
-- Konsolidiert zu einer Migration. Verifiziert: reproduziert bit-identisch das
-- von Djangos migrate erzeugte Schema (siehe PORTING_NOTES Phase 2).
--
-- WICHTIG (PORTING_NOTES Phase 2): Die Original-Migrationskette ist auf einem
-- frischen Postgres NICHT sauber anwendbar (0058/0060/0061 ProbeLog: ein
-- create->manueller DROP+fake->recreate-Tanz). Der Endzustand wurde durch
-- Nachstellen der auf Produktion gelaufenen manuellen Recovery erzeugt:
--   gui_probelog       = Schema A (probe_routes_job-Log)
--   gui_graphprobelog  = Schema B (Graph-Watcher-Log, in 0061 umbenannt)
--
-- Generiert mit Django 6.0.6 / PostgreSQL 18. IDENTITY-Spalten entsprechen
-- BigAutoField/AutoField; aeltere Django-Versionen erzeugten bigserial -
-- Spaltentyp bleibt bigint/integer (fuer sqlc identisch).

--
--

--
-- Name: gui_allowedtarget; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE gui_allowedtarget (
    id integer NOT NULL,
    target_pubkey character varying(66) NOT NULL,
    source_chan_id character varying(20) NOT NULL
);

--
-- Name: gui_allowedtarget_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE gui_allowedtarget ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME gui_allowedtarget_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: gui_ambosspeerfees; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE gui_ambosspeerfees (
    pubkey character varying(66) NOT NULL,
    mean_today double precision,
    median_today double precision,
    updated_at timestamp with time zone NOT NULL
);

--
-- Name: gui_autofees; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE gui_autofees (
    id bigint NOT NULL,
    "timestamp" timestamp with time zone NOT NULL,
    chan_id character varying(20) NOT NULL,
    peer_alias character varying(32) NOT NULL,
    setting character varying(20) NOT NULL,
    old_value integer NOT NULL,
    new_value integer NOT NULL
);

--
-- Name: gui_autofees_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE gui_autofees ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME gui_autofees_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: gui_autopilot; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE gui_autopilot (
    id bigint NOT NULL,
    "timestamp" timestamp with time zone NOT NULL,
    chan_id character varying(20) NOT NULL,
    peer_alias character varying(32) NOT NULL,
    setting character varying(20) NOT NULL,
    old_value integer NOT NULL,
    new_value integer NOT NULL
);

--
-- Name: gui_autopilot_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE gui_autopilot ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME gui_autopilot_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: gui_avoidnodes; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE gui_avoidnodes (
    pubkey character varying(66) NOT NULL,
    notes character varying(1000),
    updated timestamp with time zone NOT NULL
);

--
-- Name: gui_channels; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE gui_channels (
    remote_pubkey character varying(66) NOT NULL,
    chan_id character varying(20) NOT NULL,
    funding_txid character varying(64) NOT NULL,
    output_index integer NOT NULL,
    capacity bigint NOT NULL,
    local_balance bigint NOT NULL,
    remote_balance bigint NOT NULL,
    unsettled_balance bigint NOT NULL,
    initiator boolean NOT NULL,
    alias character varying(32) NOT NULL,
    local_base_fee integer CONSTRAINT gui_channels_base_fee_not_null NOT NULL,
    local_fee_rate integer CONSTRAINT gui_channels_fee_rate_not_null NOT NULL,
    is_active boolean NOT NULL,
    is_open boolean NOT NULL,
    auto_rebalance boolean NOT NULL,
    remote_base_fee integer NOT NULL,
    remote_fee_rate integer NOT NULL,
    local_commit integer NOT NULL,
    local_chan_reserve integer NOT NULL,
    ar_in_target integer CONSTRAINT gui_channels_ar_target_not_null NOT NULL,
    num_updates integer NOT NULL,
    ar_amt_target bigint NOT NULL,
    ar_out_target integer NOT NULL,
    ar_max_cost integer NOT NULL,
    last_update timestamp with time zone NOT NULL,
    local_disabled boolean NOT NULL,
    remote_disabled boolean NOT NULL,
    htlc_count integer NOT NULL,
    pending_inbound bigint NOT NULL,
    pending_outbound bigint NOT NULL,
    private boolean NOT NULL,
    total_received bigint NOT NULL,
    total_sent bigint NOT NULL,
    fees_updated timestamp with time zone NOT NULL,
    auto_fees boolean NOT NULL,
    local_cltv integer NOT NULL,
    remote_cltv integer NOT NULL,
    local_max_htlc_msat bigint NOT NULL,
    local_min_htlc_msat bigint NOT NULL,
    remote_max_htlc_msat bigint NOT NULL,
    remote_min_htlc_msat bigint NOT NULL,
    short_chan_id character varying(20) NOT NULL,
    notes text NOT NULL,
    close_address character varying(100) NOT NULL,
    push_amt bigint NOT NULL,
    local_inbound_base_fee integer NOT NULL,
    local_inbound_fee_rate integer NOT NULL,
    remote_inbound_base_fee integer NOT NULL,
    remote_inbound_fee_rate integer NOT NULL,
    ar_source boolean NOT NULL,
    ar_source_ppm_diff integer NOT NULL,
    inbound_offset integer NOT NULL,
    offset_updated timestamp with time zone,
    maxhtlc_percent integer NOT NULL,
    maxhtlc_updated timestamp with time zone,
    mx_liq_threshold bigint NOT NULL,
    mx_liq_value bigint NOT NULL,
    mx_liq_upper bigint NOT NULL,
    ep_target integer NOT NULL,
    ep_updated timestamp with time zone NOT NULL,
    ep_enabled boolean NOT NULL,
    ep_inc_pct double precision NOT NULL,
    ep_cooldown integer NOT NULL,
    ep_live_threshold integer NOT NULL,
    ep_live_inc_pct double precision NOT NULL,
    flp_enabled boolean NOT NULL,
    flp_safety integer NOT NULL,
    htlc_boost_checked timestamp with time zone
);

--
-- Name: gui_closures; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE gui_closures (
    id bigint NOT NULL,
    chan_id character varying(20) NOT NULL,
    funding_txid character varying(64) NOT NULL,
    funding_index integer NOT NULL,
    closing_tx character varying(64) NOT NULL,
    remote_pubkey character varying(66) NOT NULL,
    capacity bigint NOT NULL,
    close_height integer NOT NULL,
    settled_balance bigint NOT NULL,
    time_locked_balance bigint NOT NULL,
    close_type integer NOT NULL,
    open_initiator integer NOT NULL,
    close_initiator integer NOT NULL,
    resolution_count integer NOT NULL,
    closing_costs integer NOT NULL
);

--
-- Name: gui_closures_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE gui_closures ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME gui_closures_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: gui_failedhtlcs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE gui_failedhtlcs (
    id bigint NOT NULL,
    "timestamp" timestamp with time zone NOT NULL,
    amount integer NOT NULL,
    chan_id_in character varying(20) NOT NULL,
    chan_id_out character varying(20) NOT NULL,
    chan_in_alias character varying(32),
    chan_out_alias character varying(32),
    wire_failure integer NOT NULL,
    failure_detail integer NOT NULL,
    missed_fee double precision NOT NULL,
    chan_out_liq bigint,
    chan_out_pending bigint
);

--
-- Name: gui_failedhtlcs_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE gui_failedhtlcs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME gui_failedhtlcs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: gui_forwards; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE gui_forwards (
    id bigint NOT NULL,
    forward_date timestamp with time zone NOT NULL,
    chan_id_in character varying(20) NOT NULL,
    chan_id_out character varying(20) NOT NULL,
    chan_in_alias character varying(32),
    chan_out_alias character varying(32),
    amt_in_msat bigint NOT NULL,
    amt_out_msat bigint NOT NULL,
    fee double precision NOT NULL,
    inbound_fee double precision NOT NULL
);

--
-- Name: gui_forwards_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE gui_forwards ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME gui_forwards_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: gui_graphevent; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE gui_graphevent (
    id integer NOT NULL,
    "timestamp" timestamp with time zone NOT NULL,
    event_type character varying(30) NOT NULL,
    chan_id character varying(20) NOT NULL,
    capacity bigint NOT NULL,
    fee_ppm integer,
    base_fee_msat bigint NOT NULL,
    target_pubkey character varying(66) NOT NULL,
    target_alias character varying(32) NOT NULL,
    other_node character varying(66) NOT NULL,
    other_alias character varying(32) NOT NULL,
    disabled boolean NOT NULL,
    probe_triggered boolean NOT NULL,
    routes_found integer NOT NULL,
    policy_node character varying(66) NOT NULL
);

--
-- Name: gui_graphevent_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE gui_graphevent ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME gui_graphevent_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: gui_graphprobelog; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE gui_graphprobelog (
    id bigint CONSTRAINT gui_probelog_id_not_null NOT NULL,
    "timestamp" timestamp with time zone CONSTRAINT gui_probelog_timestamp_not_null NOT NULL,
    target_pubkey character varying(66) CONSTRAINT gui_probelog_target_pubkey_not_null NOT NULL,
    target_alias character varying(64) CONSTRAINT gui_probelog_target_alias_not_null NOT NULL,
    target_fee integer CONSTRAINT gui_probelog_target_fee_not_null NOT NULL,
    target_max_cost integer CONSTRAINT gui_probelog_target_max_cost_not_null NOT NULL,
    trigger_chan_id character varying(20) CONSTRAINT gui_probelog_trigger_chan_id_not_null NOT NULL,
    other_pubkey character varying(66) CONSTRAINT gui_probelog_other_pubkey_not_null NOT NULL,
    other_alias character varying(64) CONSTRAINT gui_probelog_other_alias_not_null NOT NULL,
    other_fee_ppm integer,
    budget_ppm integer CONSTRAINT gui_probelog_budget_ppm_not_null NOT NULL,
    sources_tried integer CONSTRAINT gui_probelog_sources_tried_not_null NOT NULL,
    routes_new integer CONSTRAINT gui_probelog_routes_new_not_null NOT NULL,
    routes_existing integer CONSTRAINT gui_probelog_routes_existing_not_null NOT NULL,
    errors integer CONSTRAINT gui_probelog_errors_not_null NOT NULL,
    routes_via_new_peer integer CONSTRAINT gui_probelog_routes_via_new_peer_not_null NOT NULL,
    rebalance_scheduled boolean CONSTRAINT gui_probelog_rebalance_scheduled_not_null NOT NULL,
    details text CONSTRAINT gui_probelog_details_not_null NOT NULL
);

--
-- Name: gui_histfailedhtlc; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE gui_histfailedhtlc (
    id bigint NOT NULL,
    date date NOT NULL,
    chan_id_in character varying(20) NOT NULL,
    chan_id_out character varying(20) NOT NULL,
    chan_in_alias character varying(32),
    chan_out_alias character varying(32),
    htlc_count integer NOT NULL,
    amount_sum bigint NOT NULL,
    fee_sum bigint NOT NULL,
    liq_avg bigint NOT NULL,
    pending_avg bigint NOT NULL,
    balance_count integer NOT NULL,
    downstream_count integer NOT NULL,
    other_count integer NOT NULL
);

--
-- Name: gui_histfailedhtlc_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE gui_histfailedhtlc ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME gui_histfailedhtlc_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: gui_inboundfeelog; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE gui_inboundfeelog (
    id bigint NOT NULL,
    "timestamp" timestamp with time zone NOT NULL,
    chan_id character varying(20) NOT NULL,
    peer_alias character varying(32) NOT NULL,
    setting character varying(20) NOT NULL,
    old_value integer NOT NULL,
    new_value integer NOT NULL
);

--
-- Name: gui_inboundfeelog_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE gui_inboundfeelog ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME gui_inboundfeelog_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: gui_invoices; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE gui_invoices (
    creation_date timestamp with time zone NOT NULL,
    settle_date timestamp with time zone,
    r_hash character varying(64) NOT NULL,
    value double precision NOT NULL,
    amt_paid bigint NOT NULL,
    state integer NOT NULL,
    chan_in character varying(20),
    chan_in_alias character varying(32),
    keysend_preimage character varying(64),
    message character varying(1000),
    index integer NOT NULL,
    sender character varying(66),
    sender_alias character varying(32),
    is_revenue boolean NOT NULL
);

--
-- Name: gui_localsettings; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE gui_localsettings (
    key character varying(20) NOT NULL,
    value text NOT NULL
);

--
-- Name: gui_nodecache; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE gui_nodecache (
    pubkey character varying(66) NOT NULL,
    data jsonb NOT NULL,
    updated_at timestamp with time zone NOT NULL
);

--
-- Name: gui_nodereputation; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE gui_nodereputation (
    pubkey character varying(66) NOT NULL,
    success_count integer NOT NULL,
    failure_count integer NOT NULL,
    last_success timestamp with time zone,
    last_failure timestamp with time zone
);

--
-- Name: gui_onchain; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE gui_onchain (
    tx_hash character varying(64) NOT NULL,
    amount bigint NOT NULL,
    block_hash character varying(64) NOT NULL,
    block_height integer NOT NULL,
    time_stamp timestamp with time zone NOT NULL,
    fee integer NOT NULL,
    label character varying(100) NOT NULL
);

--
-- Name: gui_paymenthops; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE gui_paymenthops (
    id bigint NOT NULL,
    attempt_id integer NOT NULL,
    step integer NOT NULL,
    chan_id character varying(20) NOT NULL,
    alias character varying(32) NOT NULL,
    chan_capacity bigint NOT NULL,
    node_pubkey character varying(66) NOT NULL,
    amt double precision NOT NULL,
    fee double precision NOT NULL,
    payment_hash_id character varying(64) NOT NULL,
    cost_to double precision NOT NULL
);

--
-- Name: gui_paymenthops_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE gui_paymenthops ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME gui_paymenthops_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: gui_payments; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE gui_payments (
    creation_date timestamp with time zone NOT NULL,
    payment_hash character varying(64) NOT NULL,
    value double precision NOT NULL,
    fee double precision NOT NULL,
    status integer NOT NULL,
    index integer NOT NULL,
    chan_out character varying(20),
    chan_out_alias character varying(32),
    keysend_preimage character varying(64),
    message character varying(1000),
    cleaned boolean NOT NULL,
    rebal_chan character varying(20)
);

--
-- Name: gui_peerevents; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE gui_peerevents (
    id bigint NOT NULL,
    "timestamp" timestamp with time zone NOT NULL,
    chan_id character varying(20) NOT NULL,
    peer_alias character varying(32) NOT NULL,
    event character varying(20) NOT NULL,
    old_value bigint,
    new_value bigint NOT NULL,
    out_liq bigint NOT NULL
);

--
-- Name: gui_peerevents_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE gui_peerevents ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME gui_peerevents_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: gui_peers; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE gui_peers (
    pubkey character varying(66) NOT NULL,
    address character varying(100) NOT NULL,
    sat_sent bigint NOT NULL,
    sat_recv bigint NOT NULL,
    inbound boolean NOT NULL,
    connected boolean NOT NULL,
    last_reconnected timestamp with time zone,
    alias character varying(32),
    ping_time bigint NOT NULL
);

--
-- Name: gui_pendingchannels; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE gui_pendingchannels (
    id bigint NOT NULL,
    funding_txid character varying(64) NOT NULL,
    output_index integer NOT NULL,
    local_base_fee integer,
    local_fee_rate integer,
    local_cltv integer,
    auto_rebalance boolean,
    ar_amt_target bigint,
    ar_in_target integer,
    ar_out_target integer,
    ar_max_cost integer,
    auto_fees boolean
);

--
-- Name: gui_pendingchannels_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE gui_pendingchannels ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME gui_pendingchannels_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: gui_pendinghtlcs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE gui_pendinghtlcs (
    id bigint NOT NULL,
    incoming boolean NOT NULL,
    amount bigint NOT NULL,
    hash_lock character varying(64) NOT NULL,
    expiration_height integer NOT NULL,
    forwarding_channel character varying(20) NOT NULL,
    alias character varying(32) NOT NULL,
    chan_id character varying(20) NOT NULL,
    forwarding_alias character varying(32) NOT NULL
);

--
-- Name: gui_pendinghtlcs_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE gui_pendinghtlcs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME gui_pendinghtlcs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: gui_probelog; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE gui_probelog (
    id integer CONSTRAINT gui_probelog_id_not_null1 NOT NULL,
    "timestamp" timestamp with time zone CONSTRAINT gui_probelog_timestamp_not_null1 NOT NULL,
    targets_scanned integer NOT NULL,
    routes_found integer NOT NULL,
    routes_existing integer CONSTRAINT gui_probelog_routes_existing_not_null1 NOT NULL,
    errors integer CONSTRAINT gui_probelog_errors_not_null1 NOT NULL,
    duration_ms integer NOT NULL,
    details jsonb CONSTRAINT gui_probelog_details_not_null1 NOT NULL
);

--
-- Name: gui_probelog_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE gui_graphprobelog ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME gui_probelog_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: gui_probelog_id_seq1; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE gui_probelog ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME gui_probelog_id_seq1
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: gui_rebalancer; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE gui_rebalancer (
    id bigint NOT NULL,
    requested timestamp with time zone NOT NULL,
    value integer NOT NULL,
    fee_limit double precision NOT NULL,
    outgoing_chan_ids text NOT NULL,
    last_hop_pubkey character varying(66) NOT NULL,
    duration integer NOT NULL,
    start timestamp with time zone,
    stop timestamp with time zone,
    status integer NOT NULL,
    payment_hash character varying(64),
    target_alias character varying(32) NOT NULL,
    manual boolean NOT NULL,
    fees_paid double precision
);

--
-- Name: gui_rebalancer_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE gui_rebalancer ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME gui_rebalancer_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: gui_rebalanceroute; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE gui_rebalanceroute (
    id bigint NOT NULL,
    target_pubkey character varying(66) NOT NULL,
    outgoing_chan_id character varying(20) NOT NULL,
    route text NOT NULL,
    final_cltv_delta integer NOT NULL,
    success_count integer NOT NULL,
    failure_count integer NOT NULL,
    last_success timestamp with time zone,
    last_failure timestamp with time zone,
    route_hex text,
    last_fee_ppm double precision
);

--
-- Name: gui_rebalanceroute_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE gui_rebalanceroute ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME gui_rebalanceroute_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: gui_resolutions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE gui_resolutions (
    id bigint NOT NULL,
    chan_id character varying(20) NOT NULL,
    resolution_type integer NOT NULL,
    outcome integer NOT NULL,
    outpoint_tx character varying(64) NOT NULL,
    outpoint_index integer NOT NULL,
    amount_sat bigint NOT NULL,
    sweep_txid character varying(64) NOT NULL
);

--
-- Name: gui_resolutions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE gui_resolutions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME gui_resolutions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: gui_tradesales; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE gui_tradesales (
    id character varying(64) NOT NULL,
    creation_date timestamp with time zone NOT NULL,
    expiry timestamp with time zone,
    description character varying(100) NOT NULL,
    price bigint NOT NULL,
    sale_type integer NOT NULL,
    secret character varying(1000),
    sale_limit integer,
    sale_count integer NOT NULL
);

--
-- Name: gui_allowedtarget gui_allowedtarget_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY gui_allowedtarget
    ADD CONSTRAINT gui_allowedtarget_pkey PRIMARY KEY (id);

--
-- Name: gui_allowedtarget gui_allowedtarget_source_chan_id_target_pubkey_63b11212_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY gui_allowedtarget
    ADD CONSTRAINT gui_allowedtarget_source_chan_id_target_pubkey_63b11212_uniq UNIQUE (source_chan_id, target_pubkey);

--
-- Name: gui_ambosspeerfees gui_ambosspeerfees_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY gui_ambosspeerfees
    ADD CONSTRAINT gui_ambosspeerfees_pkey PRIMARY KEY (pubkey);

--
-- Name: gui_autofees gui_autofees_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY gui_autofees
    ADD CONSTRAINT gui_autofees_pkey PRIMARY KEY (id);

--
-- Name: gui_autopilot gui_autopilot_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY gui_autopilot
    ADD CONSTRAINT gui_autopilot_pkey PRIMARY KEY (id);

--
-- Name: gui_avoidnodes gui_avoidnodes_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY gui_avoidnodes
    ADD CONSTRAINT gui_avoidnodes_pkey PRIMARY KEY (pubkey);

--
-- Name: gui_channels gui_channels_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY gui_channels
    ADD CONSTRAINT gui_channels_pkey PRIMARY KEY (chan_id);

--
-- Name: gui_closures gui_closures_funding_txid_funding_index_f2eff880_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY gui_closures
    ADD CONSTRAINT gui_closures_funding_txid_funding_index_f2eff880_uniq UNIQUE (funding_txid, funding_index);

--
-- Name: gui_closures gui_closures_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY gui_closures
    ADD CONSTRAINT gui_closures_pkey PRIMARY KEY (id);

--
-- Name: gui_failedhtlcs gui_failedhtlcs_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY gui_failedhtlcs
    ADD CONSTRAINT gui_failedhtlcs_pkey PRIMARY KEY (id);

--
-- Name: gui_forwards gui_forwards_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY gui_forwards
    ADD CONSTRAINT gui_forwards_pkey PRIMARY KEY (id);

--
-- Name: gui_graphevent gui_graphevent_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY gui_graphevent
    ADD CONSTRAINT gui_graphevent_pkey PRIMARY KEY (id);

--
-- Name: gui_histfailedhtlc gui_histfailedhtlc_date_chan_id_in_chan_id_out_100628eb_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY gui_histfailedhtlc
    ADD CONSTRAINT gui_histfailedhtlc_date_chan_id_in_chan_id_out_100628eb_uniq UNIQUE (date, chan_id_in, chan_id_out);

--
-- Name: gui_histfailedhtlc gui_histfailedhtlc_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY gui_histfailedhtlc
    ADD CONSTRAINT gui_histfailedhtlc_pkey PRIMARY KEY (id);

--
-- Name: gui_inboundfeelog gui_inboundfeelog_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY gui_inboundfeelog
    ADD CONSTRAINT gui_inboundfeelog_pkey PRIMARY KEY (id);

--
-- Name: gui_invoices gui_invoices_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY gui_invoices
    ADD CONSTRAINT gui_invoices_pkey PRIMARY KEY (r_hash);

--
-- Name: gui_localsettings gui_localsettings_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY gui_localsettings
    ADD CONSTRAINT gui_localsettings_pkey PRIMARY KEY (key);

--
-- Name: gui_nodecache gui_nodecache_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY gui_nodecache
    ADD CONSTRAINT gui_nodecache_pkey PRIMARY KEY (pubkey);

--
-- Name: gui_nodereputation gui_nodereputation_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY gui_nodereputation
    ADD CONSTRAINT gui_nodereputation_pkey PRIMARY KEY (pubkey);

--
-- Name: gui_onchain gui_onchain_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY gui_onchain
    ADD CONSTRAINT gui_onchain_pkey PRIMARY KEY (tx_hash);

--
-- Name: gui_paymenthops gui_paymenthops_payment_hash_id_attempt_id_step_7cbca9b1_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY gui_paymenthops
    ADD CONSTRAINT gui_paymenthops_payment_hash_id_attempt_id_step_7cbca9b1_uniq UNIQUE (payment_hash_id, attempt_id, step);

--
-- Name: gui_paymenthops gui_paymenthops_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY gui_paymenthops
    ADD CONSTRAINT gui_paymenthops_pkey PRIMARY KEY (id);

--
-- Name: gui_payments gui_payments_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY gui_payments
    ADD CONSTRAINT gui_payments_pkey PRIMARY KEY (payment_hash);

--
-- Name: gui_peerevents gui_peerevents_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY gui_peerevents
    ADD CONSTRAINT gui_peerevents_pkey PRIMARY KEY (id);

--
-- Name: gui_peers gui_peers_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY gui_peers
    ADD CONSTRAINT gui_peers_pkey PRIMARY KEY (pubkey);

--
-- Name: gui_pendingchannels gui_pendingchannels_funding_txid_output_index_6abdb03a_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY gui_pendingchannels
    ADD CONSTRAINT gui_pendingchannels_funding_txid_output_index_6abdb03a_uniq UNIQUE (funding_txid, output_index);

--
-- Name: gui_pendingchannels gui_pendingchannels_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY gui_pendingchannels
    ADD CONSTRAINT gui_pendingchannels_pkey PRIMARY KEY (id);

--
-- Name: gui_pendinghtlcs gui_pendinghtlcs_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY gui_pendinghtlcs
    ADD CONSTRAINT gui_pendinghtlcs_pkey PRIMARY KEY (id);

--
-- Name: gui_graphprobelog gui_probelog_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY gui_graphprobelog
    ADD CONSTRAINT gui_probelog_pkey PRIMARY KEY (id);

--
-- Name: gui_probelog gui_probelog_pkey1; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY gui_probelog
    ADD CONSTRAINT gui_probelog_pkey1 PRIMARY KEY (id);

--
-- Name: gui_rebalancer gui_rebalancer_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY gui_rebalancer
    ADD CONSTRAINT gui_rebalancer_pkey PRIMARY KEY (id);

--
-- Name: gui_rebalanceroute gui_rebalanceroute_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY gui_rebalanceroute
    ADD CONSTRAINT gui_rebalanceroute_pkey PRIMARY KEY (id);

--
-- Name: gui_rebalanceroute gui_rebalanceroute_target_pubkey_outgoing_c_0f0aab03_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY gui_rebalanceroute
    ADD CONSTRAINT gui_rebalanceroute_target_pubkey_outgoing_c_0f0aab03_uniq UNIQUE (target_pubkey, outgoing_chan_id, route);

--
-- Name: gui_resolutions gui_resolutions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY gui_resolutions
    ADD CONSTRAINT gui_resolutions_pkey PRIMARY KEY (id);

--
-- Name: gui_tradesales gui_tradesales_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY gui_tradesales
    ADD CONSTRAINT gui_tradesales_pkey PRIMARY KEY (id);

--
-- Name: forwards_date_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX forwards_date_idx ON gui_forwards USING btree (forward_date);

--
-- Name: forwards_in_date_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX forwards_in_date_idx ON gui_forwards USING btree (chan_id_in, forward_date);

--
-- Name: forwards_in_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX forwards_in_idx ON gui_forwards USING btree (chan_id_in);

--
-- Name: forwards_out_date_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX forwards_out_date_idx ON gui_forwards USING btree (chan_id_out, forward_date);

--
-- Name: forwards_out_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX forwards_out_idx ON gui_forwards USING btree (chan_id_out);

--
-- Name: graphevent_target_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX graphevent_target_idx ON gui_graphevent USING btree (target_pubkey);

--
-- Name: gui_allowedtarget_source_chan_id_892e0333; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX gui_allowedtarget_source_chan_id_892e0333 ON gui_allowedtarget USING btree (source_chan_id);

--
-- Name: gui_allowedtarget_source_chan_id_892e0333_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX gui_allowedtarget_source_chan_id_892e0333_like ON gui_allowedtarget USING btree (source_chan_id varchar_pattern_ops);

--
-- Name: gui_ambosspeerfees_pubkey_3a14eea9_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX gui_ambosspeerfees_pubkey_3a14eea9_like ON gui_ambosspeerfees USING btree (pubkey varchar_pattern_ops);

--
-- Name: gui_avoidnodes_pubkey_8fd932d8_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX gui_avoidnodes_pubkey_8fd932d8_like ON gui_avoidnodes USING btree (pubkey varchar_pattern_ops);

--
-- Name: gui_invoices_r_hash_84adf580_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX gui_invoices_r_hash_84adf580_like ON gui_invoices USING btree (r_hash varchar_pattern_ops);

--
-- Name: gui_localsettings_key_98ff05d5_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX gui_localsettings_key_98ff05d5_like ON gui_localsettings USING btree (key varchar_pattern_ops);

--
-- Name: gui_nodecache_pubkey_6ff0cc4f_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX gui_nodecache_pubkey_6ff0cc4f_like ON gui_nodecache USING btree (pubkey varchar_pattern_ops);

--
-- Name: gui_nodereputation_pubkey_df6595e8_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX gui_nodereputation_pubkey_df6595e8_like ON gui_nodereputation USING btree (pubkey varchar_pattern_ops);

--
-- Name: gui_onchain_tx_hash_d9063a4f_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX gui_onchain_tx_hash_d9063a4f_like ON gui_onchain USING btree (tx_hash varchar_pattern_ops);

--
-- Name: gui_paymenthops_payment_hash_id_dee5ec30; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX gui_paymenthops_payment_hash_id_dee5ec30 ON gui_paymenthops USING btree (payment_hash_id);

--
-- Name: gui_paymenthops_payment_hash_id_dee5ec30_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX gui_paymenthops_payment_hash_id_dee5ec30_like ON gui_paymenthops USING btree (payment_hash_id varchar_pattern_ops);

--
-- Name: gui_payments_payment_hash_df72c5ac_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX gui_payments_payment_hash_df72c5ac_like ON gui_payments USING btree (payment_hash varchar_pattern_ops);

--
-- Name: gui_peers_pubkey_4b15586b_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX gui_peers_pubkey_4b15586b_like ON gui_peers USING btree (pubkey varchar_pattern_ops);

--
-- Name: gui_tradesales_id_1797cc9e_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX gui_tradesales_id_1797cc9e_like ON gui_tradesales USING btree (id varchar_pattern_ops);

--
-- Name: idx_gui_channels_chan_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_gui_channels_chan_id ON gui_channels USING btree (chan_id);

--
-- Name: idx_gui_channels_rebalance; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_gui_channels_rebalance ON gui_channels USING btree (is_active, is_open, auto_rebalance);

--
-- Name: idx_gui_rebalancer_last_hop; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_gui_rebalancer_last_hop ON gui_rebalancer USING btree (last_hop_pubkey);

--
-- Name: idx_gui_rebalancer_status; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_gui_rebalancer_status ON gui_rebalancer USING btree (status);

--
-- Name: paymenthops_chanid_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX paymenthops_chanid_idx ON gui_paymenthops USING btree (chan_id);

--
-- Name: paymenthops_node_pubkey_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX paymenthops_node_pubkey_idx ON gui_paymenthops USING btree (node_pubkey);

--
-- Name: payments_chan_out_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX payments_chan_out_idx ON gui_payments USING btree (chan_out);

--
-- Name: payments_index_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX payments_index_idx ON gui_payments USING btree (index);

--
-- Name: payments_rebal_chan_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX payments_rebal_chan_idx ON gui_payments USING btree (rebal_chan);

--
-- Name: rebalroute_target_out_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX rebalroute_target_out_idx ON gui_rebalanceroute USING btree (target_pubkey, outgoing_chan_id);

--
-- Name: gui_allowedtarget gui_allowedtarget_source_chan_id_892e0333_fk_gui_chann; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY gui_allowedtarget
    ADD CONSTRAINT gui_allowedtarget_source_chan_id_892e0333_fk_gui_chann FOREIGN KEY (source_chan_id) REFERENCES gui_channels(chan_id) DEFERRABLE INITIALLY DEFERRED;

--
-- Name: gui_paymenthops gui_paymenthops_payment_hash_id_dee5ec30_fk_gui_payme; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY gui_paymenthops
    ADD CONSTRAINT gui_paymenthops_payment_hash_id_dee5ec30_fk_gui_payme FOREIGN KEY (payment_hash_id) REFERENCES gui_payments(payment_hash) DEFERRABLE INITIALLY DEFERRED;

--
--
